###GET requsest
GET https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct

###  
POST     https://63c4d1cdf80fabd877db7506.mockapi.io/newproduct
Content-Type: application/json

 {
    "name": "Long Sleeve Colorblocked Rugby Shirt",
    "img": "https://www.aeropostale.com/dw/image/v2/BBSG_PRD/on/demandware.static/-/Sites-master-catalog-aeropostale/default/dwf19be325/60721294_007_main.jpg?sw=478&sh=557&sm=fit&sfrm=jpg",
    "price": 900,
    "category": "Men",
    "colour": "Black",
    "colour_for_sorting": "Black",
    "type": "Dress",
    "Size": "L"
  }

